coderush/ViewModels/ChangeRoles.cs
using System.ComponentModel.DataAnnotations;

namespace vds.ViewModels
{
    //view model for changeroles screen
    public class ChangeRoles
    {
        public string Id { get; set; }
        [Display(Name = "ผู้ใช้")]
        public string UserName { get; set; }

        public bool IsTodoRegistered { get; set; }
        public bool IsMembershipRegistered { get; set; }
        public bool IsRoleRegistered { get; set; }
        public bool IsSelfServiceRegistered { get; set; }
        public bool IsEmployeeRegistered { get; set; }
        public bool IsSettingsRegistered { get; set; }
        public bool IsJobRegistered { get; set; }
        public bool IsDoctorRegistered { get; set; }
        public bool IsDoctorGroupRegistered { get; set; }
        public bool IsPatientRegistered { get; set; }
        public bool IsHospitalRegistered { get; set; }


        //public bool IsRecruitmentRegistered { get; set; }
        //public bool IsAttendanceRegistered { get; set; }
        //public bool IsLeaveRegistered { get; set; }
        //public bool IsAwardRegistered { get; set; }
        //public bool IsInformationRegistered { get; set; }
        //public bool IsAssetRegistered { get; set; }
        //public bool IsExpenseRegistered { get; set; }
        //public bool IsPayrollRegistered { get; set; }
        //public bool IsAppraisalRegistered { get; set; }
        //public bool IsTicketRegistered { get; set; }





    }
}

coderush/ViewModels/Register.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using vds.Models;

namespace vds.ViewModels
{
    //view model for register screen
    public class Register
    {
         
        [EmailAddress(ErrorMessage = "กรอกข้อมูลรูปแบบอีเมล์ไม่ถูกต้อง")]
        [Required(ErrorMessage = "กรุณากรอกข้อมูลอีเมล์")]
        [Display(Name = "อีเมล์")]
        public string Email { get; set; }

        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "กรอกข้อมูลรูปแบบหมายเลขโทรศัพท์ไม่ถูกต้อง")]
        [Required(ErrorMessage = "กรุณากรอกข้อมูลหมายเลขโทรศัพท์")]
        [Display(Name = "หมายเลขโทรศัพท์")]
        public string PhoneNumber { get; set; }
 
        [Display(Name = "ยืนยันอีเมล์")]
        public bool EmailConfirmed { get; set; }

        [Required(ErrorMessage = "กรุณากรอกข้อมูลรหัสผ่าน")]
        [StringLength(100, ErrorMessage = "รหัสผ่านไม่น้อยกว่า {2} ตัวอักษร และไม่เกิน {1} ตัวอักษร", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "รหัสผ่าน")]
        public string Password { get; set; }

        [Required(ErrorMessage = "กรุณากรอกข้อมูลยืนยันรหัสผ่าน")]
        [DataType(DataType.Password)]
        [Display(Name = "ยืนยันรหัสผ่าน")]
        [Compare("Password", ErrorMessage = "รหัสผ่าน 2 ครั้งไม่ตรงกัน !")]
        public string ConfirmPassword { get; set; }


        [Display(Name = "ประเภทผู้ใช้")]
        [Required(ErrorMessage = "กรุณาเลือกประเภทผู้ใช้")]
        public string UserTypeId { get; set; }

        public UserType UserType { get; set; }

    }
}

coderush/Areas/Identity/Pages/Account/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using vds.Models;
using vds.Services.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace vds.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class RegisterModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IEmailSender _emailSender;
        private readonly IdentityDefaultOptions _identityDefaultOptions;

        public RegisterModel(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ILogger<RegisterModel> logger,
            IEmailSender emailSender,
            IOptions<IdentityDefaultOptions> identityDefaultOptions
            )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
            _identityDefaultOptions = identityDefaultOptions.Value;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public void OnGet(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            //set default return url from appsettings.json
            returnUrl = _identityDefaultOptions.DefaultReturnUrl;

            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = Input.Email, Email = Input.Email };
                var result = await _userManager.CreateAsync(user, Input.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

                    //Cek appsettings.json for email auto confirmed
                    if (_identityDefaultOptions.EmailAutoConfirmed)
                    {                        
                        user.EmailConfirmed = true;
                        await _userManager.UpdateAsync(user);
                    }                    

                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    var callbackUrl = Url.Page(
                        "/Account/ConfirmEmail",
                        pageHandler: null,
                        values: new { userId = user.Id, code = code },
                        protocol: Request.Scheme);

                    await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
                        $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return LocalRedirect(returnUrl);
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

coderush/Controllers/MembershipController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Syncfusion.EJ2.Linq;
using System;
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using vds.Data;
using vds.Models;
using vds.Services;
using vds.Services.Security;
using vds.ViewModels;

namespace vds.Controllers
{
    [Authorize(Roles = Services.App.Pages.Membership.RoleName)]
    public class MembershipController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly Services.Security.ICommon _security;
        private readonly IdentityDefaultOptions _identityDefaultOptions;
        private readonly SuperAdminDefaultOptions _superAdminDefaultOptions;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly Services.App.ICommon _app;
        private IEmailSender _emailSender;

        //dependency injection through constructor, to directly access services
        public MembershipController(
            Services.Security.ICommon security,
            IOptions<IdentityDefaultOptions> identityDefaultOptions,
            IOptions<SuperAdminDefaultOptions> superAdminDefaultOptions,
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            Services.App.ICommon app,
              IWebHostEnvironment env
             
            )
        {
            _security = security;
            _identityDefaultOptions = identityDefaultOptions.Value;
            _superAdminDefaultOptions = superAdminDefaultOptions.Value;
            _context = context;
            _userManager = userManager;
            _app = app;
            _env = env;
        


        }

        //fill viewdata as dropdownlist datasource for hospital form
        private void FillDropdownListForhospitalForm()
        {
            ViewData["UserTypeId"] = _app.GetUserTypeSelectList();

        }
        public IActionResult Index()
        {

            List<UserView> users = new List<UserView>();
            var myuser = _userManager.GetUserAsync(User);
            ViewBag.UserTypeId = myuser.Result.UserTypeId;

            if (myuser.Result.UserTypeId != "0")
            {
                var appUser = _security.GetMemberByApplicationId1(_userManager.GetUserId(User));
                users.Add(appUser);
            }
            else
            {
                users = _security.GetAllMembers1();
            }

            return View(users);
        }

        //display change profile screen if member founded, otherwise 404
        [HttpGet]
        public IActionResult ChangeProfile(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IdentityUser appUser = new IdentityUser();
            appUser = _security.GetMemberByApplicationId(id);

            if (appUser == null)
            {
                return NotFound();
            }

            return View(appUser);
        }

        //post submited change profile request
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitChangeProfile([Bind("Id,EmailConfirmed,Email,PhoneNumber")] ApplicationUser applicationUser)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData[StaticString.StatusMessage] = "Error: Model state not valid.";
                    return RedirectToAction(nameof(ChangeProfile), new { id = applicationUser.Id });
                }

                ApplicationUser updatedUser = new ApplicationUser();
                updatedUser = _security.GetMemberByApplicationId(applicationUser.Id);
                if (updatedUser == null)
                {
                    TempData[StaticString.StatusMessage] = "Error: Can not found the member.";
                    return RedirectToAction(nameof(ChangeProfile), new { id = applicationUser.Id });
                }

                if (_identityDefaultOptions.IsDemo && _superAdminDefaultOptions.Email.Equals(applicationUser.Email))
                {
                    TempData[StaticString.StatusMessage] = "Error: Demo mode can not change super@admin.com data.";
                    return RedirectToAction(nameof(ChangeProfile), new { id = applicationUser.Id });
                }

                updatedUser.Email = applicationUser.Email;
                updatedUser.PhoneNumber = applicationUser.PhoneNumber;
                updatedUser.EmailConfirmed = applicationUser.EmailConfirmed;

                _context.Update(updatedUser);
                await _context.SaveChangesAsync();

                TempData[StaticString.StatusMessage] = "บันทึกข้อมูลเรียบร้อย!";
                return RedirectToAction(nameof(ChangeProfile), new { id = updatedUser.Id });
            }
            catch (Exception ex)
            {
                TempData[StaticString.StatusMessage] = "Error: " + ex.Message;
                return RedirectToAction(nameof(ChangeProfile), new { id = applicationUser.Id });
            }

        }

        //display change password screen if user founded, otherwise 404
        [HttpGet]
        public IActionResult ChangePassword(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = _security.GetMemberByApplicationId(id);
            if (member == null)
            {
                return NotFound();
            }

            ResetPassword cp = new ResetPassword();
            cp.Id = id;
            cp.UserName = member.UserName;

            return View(cp);
        }

        //post submitted change password request
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitChangePassword([Bind("Id,OldPassword,NewPassword,ConfirmPassword")] ResetPassword changePassword)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData[StaticString.StatusMessage] = "Error: Model state not valid.";
                    return RedirectToAction(nameof(ChangePassword), new { id = changePassword.Id });
                }

                var member = _security.GetMemberByApplicationId(changePassword.Id);

                if (member == null)
                {
                    TempData[StaticString.StatusMessage] = "Error: Can not found the member.";
                    return RedirectToAction(nameof(ChangePassword), new { id = changePassword.Id });
                }

                if (_identityDefaultOptions.IsDemo && _superAdminDefaultOptions.Email.Equals(member.Email))
                {
                    TempData[StaticString.StatusMessage] = "Error: Demo mode can not change super@admin.com data.";
                    return RedirectToAction(nameof(ChangePassword), new { id = changePassword.Id });
                }
                var tokenResetPassword = await _userManager.GeneratePasswordResetTokenAsync(member);
                var changePasswordResult = await _userManager.ResetPasswordAsync(member, tokenResetPassword, changePassword.NewPassword);
                if (!changePasswordResult.Succeeded)
                {
                    TempData[StaticString.StatusMessage] = "Error: ";
                    foreach (var error in changePasswordResult.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                        TempData[StaticString.StatusMessage] = TempData[StaticString.StatusMessage] + " " + error.Description;
                    }
                    return RedirectToAction(nameof(ChangePassword), new { id = changePassword.Id });
                }

                TempData[StaticString.StatusMessage] = "Reset password success";
                return RedirectToAction(nameof(ChangePassword), new { id = changePassword.Id });
            }
            catch (Exception ex)
            {
                TempData[StaticString.StatusMessage] = "Error: " + ex.Message;
                return RedirectToAction(nameof(ChangePassword), new { id = changePassword.Id });
            }

        }

        //display change role screen if user founded, otherwise 404
        [HttpGet]
        public async Task<IActionResult> ChangeRole(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = _security.GetMemberByApplicationId(id);
            if (member == null)
            {
                return NotFound();
            }

            var registeredRoles = await _userManager.GetRolesAsync(member);

            ChangeRoles changeRole = new ChangeRoles();
            changeRole.Id = id;
            changeRole.UserName = member.UserName;



            //changeRole.IsSelfServiceRegistered = registeredRoles.Contains("SelfService") ? true : false;
            //changeRole.IsRecruitmentRegistered = registeredRoles.Contains("Recruitment") ? true : false;
            //changeRole.IsAttendanceRegistered = registeredRoles.Contains("Attendance") ? true : false;
            //changeRole.IsLeaveRegistered = registeredRoles.Contains("Leave") ? true : false;
            //changeRole.IsAwardRegistered = registeredRoles.Contains("Award") ? true : false;
            //changeRole.IsInformationRegistered = registeredRoles.Contains("Information") ? true : false;
            //changeRole.IsAssetRegistered = registeredRoles.Contains("Asset") ? true : false;
            //changeRole.IsExpenseRegistered = registeredRoles.Contains("Expense") ? true : false;
            //changeRole.IsPayrollRegistered = registeredRoles.Contains("Payroll") ? true : false;

coderush/Views/Membership/ChangePassword.cshtml
@model ResetPassword
@{
    ViewData["Title"] = "Change Password";
    string controller = this.ViewContext.RouteData.Values["controller"].ToString();
}

<!-- Content Start -->
<div class="content-wrapper">
    <!-- Heading Start -->
    <section class="heading">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/@controller/index">ผู้ใช้งานระบบ</a></li>
            <li class="breadcrumb-item active">เปลี่ยนรหัสผ่าน</li>
        </ul>
        <h2 class="mb-2"><i class="mdi mdi-account-settings-variant"></i>เปลี่ยนรหัสผ่าน</h2>
        <div class="titles">
            @await Html.PartialAsync(PartialView.StatusMessage, TempData[StaticString.StatusMessage])
        </div>
    </section><!-- Heading End -->
    <div class="row">
        <div class="col-12">
            <form asp-controller="Membership" asp-action="SubmitChangePassword" method="post">
                <article class="card mb-4">
                    <div class="card-header">
                        <h4 class="card-title mb-0">รายละเอียดผู้ใช้งานระบบ</h4>
                    </div>
                    <div class="card-body">
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="UserName">ผู้ใช้</label>
                            <input asp-for="UserName" class="form-control" disabled />
                        </div>
                        <div class="form-group">
                            <label asp-for="NewPassword">รหัสผ่านใหม่</label>
                            <input asp-for="NewPassword" class="form-control" autocomplete="new-password" />
                            <span asp-validation-for="NewPassword" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ConfirmPassword">ยืนยันรหัสผ่าน</label>
                            <input asp-for="ConfirmPassword" class="form-control" autocomplete="off" />
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="/Membership/Index" class="btn btn-default">ย้อนกลับ</a>
                        <button type="submit" class="btn btn-primary">เปลี่ยนรหัสผ่าน</button>
                    </div>
                </article>
            </form>
        </div>
    </div>
</div>
<!-- Content End -->

@section Styles{

}

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

coderush/Views/Membership/ChangeProfile.cshtml
@using Microsoft.AspNetCore.Identity
@model IdentityUser

@{
    ViewData["Title"] = "แก้ไขข้อมูลผู้ใช้";
    string controller = this.ViewContext.RouteData.Values["controller"].ToString();
}

<!-- Content Start -->
<div class="content-wrapper">
    <!-- Heading Start -->
    <section class="heading">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/@controller/index">ผู้ใช้งานระบบ</a></li>
            <li class="breadcrumb-item active">ข้อมูลผู้ใช้</li>
        </ul>
        <h2 class="mb-2"><i class="mdi mdi-account-settings-variant"></i>@ViewData["Title"]</h2>
        <div class="titles">
            @await Html.PartialAsync(PartialView.StatusMessage, TempData[StaticString.StatusMessage])
        </div>
    </section><!-- Heading End -->
    <div class="row">
        <div class="col-12">
            <form asp-controller="Membership" asp-action="SubmitChangeProfile" method="post">
                <article class="card mb-4">
                    <div class="card-header">
                        <h4 class="card-title mb-0">รายละเอียดผู้ใช้งานระบบ</h4>
                    </div>
                    <div class="card-body">
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="UserName">ผู้ใช้</label>
                            <input asp-for="UserName" class="form-control" disabled />
                        </div>
                        <div class="form-group">
                            <label asp-for="Email">อีเมล์</label>
                            <div class="input-group">
                                <input asp-for="Email" class="form-control" />
                                <span class="input-group-addon" aria-hidden="true"><span class="glyphicon glyphicon-ok text-success"></span></span>
                            </div>
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PhoneNumber">หมายเลขโทรศัพท์</label>
                            <input asp-for="PhoneNumber" class="form-control" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Active</label>
                            <div class="form-check">
                                <label class="custom-checkbox variation3 mb-0">
                                    <input asp-for="EmailConfirmed" class="form-check-input" />
                                    <i class="input-helper"></i>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="/Membership/Index" class="btn btn-default">ย้อนกลับ</a>
                        <button type="submit" class="btn btn-primary">บันทึก</button>
                    </div>
                </article>
            </form>
        </div>
    </div>
</div>
<!-- Content End -->

@section Styles{

}

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

coderush/Views/Membership/Register.cshtml
@using vds.ViewModels
@model Register

@{
    ViewData["Title"] = "Register";
    string controller = this.ViewContext.RouteData.Values["controller"].ToString();
    bool sendemail = true;
}

<!-- Content Start -->
<div class="content-wrapper">
    <!-- Heading Start -->
    <section class="heading">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/@controller/index">ผู้ใช้งานระบบ</a></li>
            <li class="breadcrumb-item active">ลงทะเบีนผู้ใช้</li>
        </ul>
        <h2 class="mb-2"><i class="mdi mdi-account-settings-variant"></i> ลงทะเบียนผู้ใช้งาน</h2>
        <div class="titles">
            @await Html.PartialAsync(PartialView.StatusMessage, TempData[StaticString.StatusMessage])
        </div>
    </section><!-- Heading End -->
    <div class="row">
        <div class="col-12">
            <form asp-controller="Membership" asp-action="SubmitRegister" method="post">
                <article class="card mb-4">
                    
                    <div class="card-body">

                        <div class="form-group">
                            <label asp-for="UserTypeId"></label>
                            <div class="input-group">
                                <select asp-for="UserTypeId" class="select2 form-control" asp-items="ViewBag.UserTypeId"></select>
                                <span class="input-group-addon" aria-hidden="true"><span class="glyphicon glyphicon-ok text-success"></span></span>
                            </div>
                            <span asp-validation-for="UserTypeId" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Email"></label>
                            <div class="input-group">
                                <input asp-for="Email" class="form-control" autocomplete="off" />
                                <span class="input-group-addon" aria-hidden="true"><span class="glyphicon glyphicon-ok text-success"></span></span>
                            </div>
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PhoneNumber"></label>
                            <input asp-for="PhoneNumber" class="form-control" autocomplete="off" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Active</label>
                            <div class="form-check">
                                <label class="custom-checkbox variation3 mb-0">
                                    <input asp-for="EmailConfirmed" class="form-check-input" />
                                    <i class="input-helper"></i>
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Password"></label>
                            <input asp-for="Password" class="form-control" autocomplete="new-password" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ConfirmPassword"></label>
                            <input asp-for="ConfirmPassword" class="form-control" autocomplete="off" />
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>ส่งอีเมล์อัตโนมัติ เพื่อแจ้งผู้ใช้ที่กำหนด</label>
                            <div class="form-check">
                                <label class="custom-checkbox variation3 mb-0">
                                    <input asp-for="@sendemail" class="form-check-input" />
                                    <i class="input-helper"></i>
                                </label>
                            </div>
                        </div>
                        
                    </div>
                    <div class="card-footer">
                        <a href="/Membership/Index" class="btn btn-default">ย้อนกลับ</a>
                        <button type="submit" class="btn btn-primary">บันทึก</button>
                    </div>
                </article>
            </form>
        </div>
    </div>
</div>
<!-- Content End -->

@section Styles{

}

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}